apiVersion: v1
kind: ConfigMap
metadata:
  name: shifty-config
data:
  config.json: |-
    global
      maxconn 50000
      log /dev/log local0
      user haproxy
      group haproxy
      stats socket /run/haproxy/admin.sock user haproxy group haproxy mode 660 level admin
      nbproc 2
      nbthread 4
      cpu-map auto:1/1-4 0-3
      ssl-default-bind-ciphers ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256
      ssl-default-bind-options ssl-min-ver TLSv1.2 no-tls-tickets

    frontend www.mysite.com
      bind 10.0.0.3:80
      bind 10.0.0.3:443 ssl crt /etc/ssl/certs/mysite.pem
      http-request redirect scheme https unless { ssl_fc }
      use_backend api_servers if { path_beg /api/ }
      default_backend web_servers
