# Default values for kubetoy.
replicaCount: 3
image:
  repository: ibmicpcoc/kubetoy
  pullPolicy: IfNotPresent
service:
  name: kubetoy-service
  type: NodePort
  externalPort: 80
storage:
  pvc: kubetoy-pvc
  accessmode: ReadWriteMany
